# Generated by Django 4.0.4 on 2022-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogYoga', '0006_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extracto',
            field=models.CharField(default='Leer más', max_length=200),
        ),
    ]
